Asp.Net6/Controllers/AlumnoController.cs
using Asp.Net6.Data;
using Asp.Net6.Models;
using Microsoft.AspNetCore.Mvc;

namespace Asp.netCore6.Controllers
{
    public class AlumnoController : Controller
    {
        //variable privada 
        private readonly ApplicationDbContext _db;

        //Constructor
        public AlumnoController(ApplicationDbContext db)
        {
            _db = db;     
        }

        public IActionResult Index()
        {
            //Extraer lista de datos de Alumnos 
            IEnumerable<Alumno> lista = _db.Alumno;
            return View(lista);
        }
        
        //Get Crear
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Crear(Alumno alumno)
        {
            //Validación
            /*Si el modelo es válido, se graban los datos y retorna la vista*/
            if (ModelState.IsValid)
            {
                _db.Alumno.Add(alumno);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            /*Sino se retorna a la misma vista crear pero se le envia los datos ingresados en alumno*/
            return View(alumno);

        }

        //Get Editar
        public IActionResult Editar(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            //Se captura al Alumno por el Id
            var editarobj = _db.Alumno.Find(Id);
            //Si el obj es null, que tambien retorne NotFound
            if (editarobj == null)
            {
                return NotFound();
            }
            //Si no es Null, retornamos obj a la vista
            return View(editarobj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(Alumno alumno)
        {
            if (ModelState.IsValid)
            {
                _db.Alumno.Update(alumno);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            /*Sino se retorna a la misma vista crear pero se le envia los datos ingresados en alumno*/
            return View(alumno);

        }

        //Get Elminar
        public IActionResult Eliminar(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            //Se captura al Alumno por el Id
            var eliminarobj = _db.Alumno.Find(Id);
            //Si el obj es null, que tambien retorne NotFound
            if (eliminarobj == null)
            {
                return NotFound();
            }
            //Si no es Null, retornamos obj a la vista
            return View(eliminarobj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Eliminar(Alumno alumno)
        {
            if (alumno == null)
            {
                return NotFound();
            }
            _db.Alumno.Remove(alumno);
            _db.SaveChanges();
            return RedirectToAction("Index");


        }
    }
}

Asp.Net6/Controllers/CursoController.cs
using Asp.Net6.Data;
using Asp.Net6.Models;
using Microsoft.AspNetCore.Mvc;

namespace Asp.Net6.Controllers
{
    public class CursoController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CursoController( ApplicationDbContext db)
        {
            _db= db;
        }

        public IActionResult Index()
        {
            IEnumerable<Curso> lista = _db.Curso;
            return View(lista);
        }

        //Get Crear
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Crear(Curso curso)
        {
            //Validación
            if (ModelState.IsValid)
            {
                _db.Curso.Add(curso);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(curso);

        }

        //Get Editar
        public IActionResult Editar(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var editarobj = _db.Curso.Find(Id);
            if (editarobj == null) 
            {
                return NotFound();
            }
            return View(editarobj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(Curso curso)
        {

            if (ModelState.IsValid)
            {
                _db.Curso.Update(curso);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(curso);

        }

        //Get Eliminar
        public IActionResult Eliminar(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var eliminarobj = _db.Curso.Find(Id);
            if (eliminarobj == null)
            {
                return NotFound();
            }
            return View(eliminarobj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Eliminar(Curso curso)
        {

            if (curso == null)
            {
                return NotFound();
            }
            _db.Curso.Remove(curso);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

    }
}

Asp.Net6/Controllers/NotaController.cs
using Asp.Net6.Data;
using Asp.Net6.Models;
using Asp.Net6.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace Asp.Net6.Controllers
{
    public class NotaController : Controller
    {
        //atributo 
        private readonly ApplicationDbContext _db;
        //Constructor
        public NotaController( ApplicationDbContext db)
        {
            _db= db;
        }


        public IActionResult Index()
        {
            //Incluimos las Listas de Alumno y Curso enlazados a la Nota con el Include
            IEnumerable<Nota> lista = _db.Nota.Include(a => a.Alumno)
                                              .Include(c => c.Curso);
            return View(lista);
        }

        public IActionResult Filtrar(int Id)
        {
            IQueryable<Nota> listaFiltrada = _db.Nota.Include(a => a.Alumno)
                                                     .Include(c => c.Curso).Where(c => c.Curso.Id == Id);

            return View(listaFiltrada);
        }


        //Get Crear/Editar
        public IActionResult Upsert(int? Id)
        {
            //Crear las Listas de Alumno - Curso 
            NotaVM notaVM = new NotaVM()
            {
                Nota = new Nota(),
                AlumnoLista = _db.Alumno.Select(a => new SelectListItem
                {
                    Text = a.NombreApellido,
                    Value = a.Id.ToString()
                }),
                CursoLista = _db.Curso.Select(c => new SelectListItem
                {
                    Text = $"{c.Comision} - {c.Materia}",
                    Value = c.Id.ToString()
                })

            };


            if (Id == null)
            {
                //Crear nueva Nota
                return View(notaVM);
            }
            else
            {
                //Editar Nota
                notaVM.Nota =  _db.Nota.Find(Id);
                if (notaVM.Nota == null)
                {
                    return NotFound();
                }
                return View(notaVM);
            }
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(NotaVM notaVM)
        {
            if (ModelState.IsValid)
            {
                if (notaVM.Nota.Id == 0)
                {
                    //Crear
                    _db.Nota.Add(notaVM.Nota);
                }
                else
                {
                    //Actualizar       
                    _db.Nota.Update(notaVM.Nota);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            //Si no es Valido
            /*Se llenan nuevamente las listas si algo falla*/
            notaVM.AlumnoLista = _db.Alumno.Select(a => new SelectListItem
            {
                Text = a.NombreApellido,
                Value = a.Id.ToString()
            });
            notaVM.CursoLista = _db.Curso.Select(c => new SelectListItem
            {
                Text = $"{c.Comision} - {c.Materia}",
                Value = c.Id.ToString()
            });

            return View(notaVM);
 
        }

        //Get Eliminar
        public IActionResult Eliminar(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            Nota nota = _db.Nota.Include(a => a.Alumno)
                                 .Include(c => c.Curso)
                                 .FirstOrDefault(n=>n.Id == Id);

            if (nota == null)
            {
                return NotFound();
            }
            return View(nota);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Eliminar(Nota nota)
        {
            if (nota == null)
            {
                return NotFound();
            }
            _db.Nota.Remove(nota);
            _db.SaveChanges();
            return RedirectToAction("Index");
        
        }
    }
}

Asp.Net6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asp.Net6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Asp.Net6.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/d73c5ff364.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Asp.Net6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alumno" asp-action="Index">Alumnos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso" asp-action="Index">Cursos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nota" asp-action="Index">Notas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Asp.Net6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>